### ISSUE TITLE
Include tables

### ISSUE THREAD

**Issue by ishiikurisu** [ishiikurisu/failproof-server#14]
# About

Tables should follow the Github Flavored Markdown format and should be extensible somehow.

# Tasks

- [x] Include tables on FPCL
- [x] Allow tables to be expanded by scripting
- [x] Select scripting language
- [ ] Include tables on web interface

**Comment by ishiikurisu** [comment]
# Suggestion regarding table extension

This is a regular Markdown table:

``` md
| name | age |
|------|-----|
| Joe | 26 |
| Bayul | 23 |
| Raff | 16 |
```

Columns could included on the table by adding a new `:` block that would follow the table. Let's say we pick Python as the scripting language, then we could have something like this:

``` md
| name | age |
|------|-----|
| Joe | 26 |
| Bayul | 23 |
| Raff | 16 |
: title = [f"{row['name']}, aged {row['age']}" for row in table]
```

generating the following table:

| name | age | title |
|------|-----|--------|
| Joe | 26 | Joe, aged 26 |
| Bayul | 23 | Bayul, aged 23 |
| Raff | 16 | Raff, aged 16 |

**Comment by ishiikurisu** [comment]
Included another task to select the scripting language. Initial ideas include:

- [Ruby](https://opalrb.com/)
- [Python](http://pyjs.org/)
- Javascript
